version: '3.8'

services:
  bkmimari_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bkmimari_nextjs
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOSTNAME=172.16.16.13
      - MINIO_RAW_ENDPOINT=172.16.16.90
      - MINIO_PORT=6000
      - MINIO_USE_SSL=false
      - MINIO_PUBLIC_URL=https://minio.bkmimari.com
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=818wlxjncI6J80
      - MINIO_BUCKET=bkmimari
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
