version: '3.8'

services:
  bkmimari_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bkmimari_nextjs
    ports:
      - "172.16.16.13:8080:3000"
    restart: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
